# config-version: 2

name: 'asana_source'
version: '0.0.1'

require-dbt-version: [">=0.16.0", "<0.18.0"]

models:
    asana_source:
        materialized: table # ephemeral after testing

vars:
    asana_source:
        # asana_database: dbt-package-testing
        # asana_schema: asana
        user: "{{ source('asana', 'user') }}"        


# delete profile after testing
profile: dev_bigquery_dbt_testing